apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fgnl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fgnl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fgnl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fgnl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fgnl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mjaz-tenant/rhtap-demo-app/hacbs-test-project-fgnl@sha256:d67d941852075829c95ac6dc7962b2c15e8ea65f7dce63999b590f2919a4f4c3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
