apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fgnl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mjaz-tenant/rhtap-demo-app/hacbs-test-project-fgnl@sha256:32f58f91f539c7b8410ad79aba01a54425da3a6c996f9911da81f86f4bb0d15f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
